name: cd_lambda

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "infra/lambroll/**"
      - "lambda/src/**"
      - "docker/lambda/Dockerfile"
      - ".github/workflows/cd_lambda.yml"
  workflow_dispatch:

env:
  PLATFORM: linux/arm64
  DOCKERFILE_PATH: docker/lambda/Dockerfile
  AWS_REGION: ap-northeast-1
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/sample-lambda-cicd-dev-github-actions-oidc-role
  AWS_ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  AWS_ECR_REPOSITORY: sample-lambda-cicd-dev-lambda

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORM }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AWS_ECR_REGISTRY }}

      - name: Build and push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.AWS_ECR_REGISTRY }}/${{ env.AWS_ECR_REPOSITORY }}:${{ github.sha }}
          platforms: ${{ env.PLATFORM }}
          target: runner
          provenance: false
